config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :users, only: [ :create, :show, :index, :new]
  resources :cats, only: [ :index, :show, :new, :create, :edit, :update, :destroy]

  resources :cat_rental_requests, only: [ :new, :create]
    root to: 'cats#index'



   patch 'cat_rental_requests/:id/deny', :to => 'cat_rental_requests#deny', as: 'cat_rental_deny'
   patch 'cat_rental_requests/:id/approve', :to => 'cat_rental_requests#approve', as: 'cat_rental_approve'



   get 'session', :to => 'sessions#new', as: 'login'
   post 'session', to: 'sessions#create'
   delete 'session', :to => 'sessions#destroy'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  SEX = ['m', 'f']
  COLORS = ['black', 'brown', 'orange', 'grey', 'white', 'orange with black strips' ]
  validates :color, :name, :sex, :presence => true
  validates :color, :inclusion =>  { in: COLORS }
  validates :sex, :inclusion =>    { in: SEX }

  def age
    Time.new.year - birth_date.year
  end


  has_many :cat_rental_requests, dependent: :destroy





end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUS = %w( APPROVED DENIED PENDING)

  validates :cat_id, :start_date, :end_date, :presence => true
  validates :status, :inclusion => { in: STATUS }
  validate :overlapping_approved_requests



  belongs_to :cat



  def overlapping_requests
    CatRentalRequest
      .where('cat_id = ?', self.cat_id)
      .where('NOT(? < start_date OR ? > end_date)', self.end_date, self.start_date)
  end

  def overlapping_approved_requests

    if overlapping_requests.exists?(status: 'APPROVED')
      errors[:status] << 'overlap'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :session_token, presence: true, uniqueness: true
  validates :user_name, uniqueness: true, presence: true
  validates :password_digest, presence: true
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  after_initialize :set_session_token

  def self.create_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def reset_session_token!
    self.session_token = User.create_session_token
    self.save!
    self.session_token

  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def set_session_token
    self.session_token ||= User.create_session_token
  end


  





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user


  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    session[:session_token]=nil
  end
  def logged_in?
    !!current_user
  end

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  # logged_in? helper method
  # current_user helper method

end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cat_rental_request = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(request_params)
    if @cat_rental_request.save
      @cat_rental_request.update(:status => 'APPROVED')
      redirect_to cat_url(@cat_rental_request.cat_id)
    else
      @cats = Cat.all
      flash.now[:errors] = @cat_rental_request.errors.full_messages
      render :new
    end
  end

  def deny
    request = CatRentalRequest.find(params[:id])
    request.update!(:status => 'DENIED')
    redirect_to cat_url(request.cat_id)
  end

  def approve
    request = CatRentalRequest.find(params[:id])
    request.update!(:status => 'APPROVED')
    redirect_to cat_url(request.cat_id)
  end

  private

  def request_params
    params[:cat_rental_request].permit(:start_date, :end_date, :cat_id)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    if logged_in?
      @cat = Cat.find(params[:id])
      @approved_requests = @cat.cat_rental_requests.where("status = 'APPROVED'").order('start_date')
      @pending_requests = @cat.cat_rental_requests.where("status = 'PENDING'").order('start_date')
      render :show
    else
      redirect_to session_url
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    cat = Cat.new(cat_params)
    if cat.save
      redirect_to cat_url(cat.id)
    else
      # @attributes = cat_params
      render :new
    end
  end

  def update
    cat = Cat.find(params[:id])
    cat.update(cat_params)
    redirect_to cat_url(cat)
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def destroy
    Cat.find(params[:id]).destroy
    redirect_to cats_url
  end

  private

  def cat_params
    params[:cat].permit(:birth_date, :description, :sex, :name, :color)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def destroy
    logout
    redirect_to cats_url
  end

    # verify username/password
    # reset session token
    # update the session
    # redirect user to cats index

    # verify
  def create
    user = User.find_by_credentials(*user_params.values)
    if user
      login(user)
      redirect_to cats_url
    else
      redirect_to login_url
    end


  end

  def user_params
    params[:user].permit(:user_name, :password)
  end


  private

  def logout
    session[:session_token] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    render json: User.all
  end

  def show
    render json: User.find(params[:id])
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to cats_url
    else
    render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
  def cat_default_sex(default_sex)
    @cat.sex == default_sex ? 'checked' : 'unchecked'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<ul>
  <% flash[:errors].to_a.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<form action="<%=cat_rental_requests_url%>" method="post">

<label for="cat_id">Select a Cat!</label><br>
 <select name="cat_rental_request[cat_id]">
   <option value = ''>our cats!</option>
   <% @cats.each do |cat| %>
    <option value= "<%=cat.id%>" > <%= cat.name %></option>
    <% end %>
 </select><br>
 <label for="cat_rental_request_start_date">Start Date</label><br>
 <input name="cat_rental_request[start_date]" id="cat_rental_request_start_date" type="date", value= <%=@cat_rental_request.start_date %>>
 </input><br>

 <label for="cat_rental_request_end_date">End Date</label><br>
 <input name="cat_rental_request[end_date]" id="cat_rental_request_end_date" type="date", value= <%=@cat_rental_request.end_date %>>
 </input>

 <button >Submit</button>
</form>

app/views/cats/_form.html.erb
<% if  @cat.id%>
  <h1>Edit your cat!</h1>
<% else %>
  <h1>Create a cat! </h1>
<% end %>
<!-- edit: cat_url(@cat)
 -->
<!-- new: cats_url -->
<% if  @cat.id%>
  <form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="Patch">
<% else %>
  <form action="<%= cats_url %>" method="post">
<% end %>

<!-- name -->
<label for="cat_name">Name</label><br>
<textarea name="cat[name]" id = 'cat_name' row = 1 ><%= @cat.name %></textarea><br>

<!-- color -->
<label for="cat_color">Color</label><br>



<select name="cat[color]">
  <% temp = @cat.class::COLORS %>
  <% temp.unshift(temp.delete(@cat.color)) %>
  <% temp.each do |color| %>
    <% if color.nil? %>
      <option value= "">Select color</option>
    <% else %>
      <option value= "<%= color %>" ><%= color %></option>
    <% end %>
  <% end %>
 </select><br>

<label for="cat_birth_date">Birth day</label><br>
<input name="cat[birth_date]" id="cat_birth_date" type="date"
  value=<%= @cat.birth_date %>></input><br>

<label>Sex</label>
 <!-- note that both radio buttons have the name `cat[sex]`; that's how
      they are related -->


 <input name="cat[sex]" id="cat_sex_m" type="radio" value="m"
        <%= cat_default_sex('m') %>>
 <label for="cat_sex_m">Male</label>
 <input name="cat[sex]" id="cat_sex_f" type="radio" value="f"
          <%= cat_default_sex('f') %>>
 <label for="cat_sex_f">Female</label>
 <br>

<label for="cat_description">Describe your cat!</label><br>
<textarea name="cat[description]" id = "cat_description" rows = 20 cols = 50>
  <%= @cat.description %>
</textarea><br>

<input type="submit" value="Submit">

</form>

app/views/cats/edit.html.erb
<%= render("form", cat: @cat) %>

app/views/cats/index.html.erb
<%if logged_in? %>
<h1><%= "hello #{current_user.user_name}"%><h1>
<form action="<%= session_url%>" method="POST">
<input type="submit" value="Log Out">
<input type="hidden" name="_method" value="DELETE">
</form>
<%end  %>

<h1>All our Cats!</h1>
  <ul>
    <% @cats.each do |cat| %>
      <li><a href= "<%= cat_url(cat) %>"> <%= cat.name %></a> </li>
    <% end %>
  </ul>

app/views/cats/new.html.erb
<!-- _method: patch -->
<!-- radio buttons -->
<!-- dropdown for color -->
<!-- date input type -->
<!-- set default color to blank option -->
<!-- textarea for description -->


<%= render( "form", cat: @cat ) %>

app/views/cats/show.html.erb
<h1> <%= @cat.name %> </h1>

<table>
  <tr>
    <th>color</th>
    <th>age   </th>
    <th>sex</th>

  </tr>
  <tr>
    <td><%= @cat.color %></td>
    <td><%= @cat.age %></td>
    <td> <%= @cat.sex %></td>
  </tr>
</table>
<h2> Rented Dates <h2>
  <ul>
    <li>start date, end date, status</li>
    <% @approved_requests.each do |request| %>
      <li><%= request.start_date %>, <%= request.end_date %>,  <%= request.status %></li>
    <% end %>
  </ul>

<h2> Description</h2>
<%= @cat.description %><br>

<a href="<%=edit_cat_url(@cat)%>">Edit Cat</a>

<form action="<%=cat_url(@cat)%>" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Destroy this cat">
</form>

<h2> Pending Dates <h2>
  <ul>
    <li>start date, end date</li>
    <% @pending_requests.each do |request| %>
      <li><%= request.start_date %>, <%= request.end_date %>
      <form method='post' action='  <%= cat_rental_deny_url(request.id) %>'>
        <input type="hidden" name="_method" value='PATCH'>
        <input type="submit" value="deny"></form></li>

      <form method='post' action='  <%= cat_rental_approve_url(request.id) %>'>
        <input type="hidden" name="_method" value='PATCH'>
        <input type="submit" value="approve"></form></li>


      <!-- add dropdown for approving or denying a request -->
      <!-- TODO: remove auto approval removal -->
      <!-- TODO: auto remove pending requests with overlapping dates -->
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%=users_url%>" method="post">
  <label for="user_user_name"> input username</label>
  <input type="text" name="user[user_name]" id="user_user_name"><br>
  <label for="user_password"> input password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>
  <input type="submit" value="Submit">
</form>